version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 1,5"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      npm-minor-and-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 1,5"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
